[package]
name = "lifefromscratch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
minifb = "0.28.0"
minifb_fonts = "0.1.3"
minifb_geometry = "0.1.1"





