project:
  type: website
  output-dir: ../docs

website:
  title: Life from Scratch Development Log
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - section: "CMPLXSYS 530"
        contents:
        - proposal.qmd
        - href: finalpaper.qmd
          text: Final Paper
      - section: "Utilities"
        contents:
        - chemgen.qmd

bibliography: bibliography/proposal.bib

format:
  html:
    theme: 
      - simplex
      - custom-light.scss

